version: '3.9'

services:
  app:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./App:/App
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=john
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=your_lunch